### ISSUE TITLE
佬，麻烦有空的时候看一下

### ISSUE THREAD

**Issue by entaroartanis114514** [RiderLty/fontInAss#1]
今天更新后docker版后fontinass出现下面的错误，EMBY的WEB界面会出现无法兼容的流  客户端会没有字幕。
2024/09/01 00:04:11 | stderr | 2024/08/31 16:04:11 [error] 16#16: *1 js exception: Error: unhandled promise rejection: ReferenceError: "debug" is not defined
还有一个问题
之前的版本如果是srt字幕的情况我这里使用nginx或者lucky反代8012端口到443通过域名访问都会不显示srt字幕，客户端会直接卡住  web会不显示srt字幕，如果切换成ASS或者PSG就正常。
佬，你看下我这里需要提供什么吗？

**Comment by entaroartanis114514** [comment]
佬，我更正一下错误信息,。之前发的错误信息少了一段
2024/09/01 12:54:42 | stderr | , client: 172.17.0.1, server: , request: "GET /emby/Videos/38658/b0e3530e9e59e286c59657cca8c2c4ec/Subtitles/4/0/Stream.vtt?api_key=apikey HTTP/1.1", host: "域名", referrer: "https://域名/web/index.html"
2024/09/01 12:54:42 | stderr | at anonymous (/etc/nginx/conf.d/emby.js:4)
2024/09/01 12:54:39 | stderr | 2024/09/01 04:54:39 [error] 11#11: *1208 js exception: Error: unhandled promise rejection: ReferenceError: "debug" is not defined

**Comment by RiderLty** [comment]
DEBUG这个是昨天添加功能，忘记给去掉了，现在更新下容器应该就好了。

SRT如果没有设置SRT_2_ASS_FORMAT与SRT_2_ASS_STYLE应该是直接报错，然后返回原始内容。
如果设置了SRT_2_ASS_FORMAT与SRT_2_ASS_STYLE，会将SRT转为ASS传递给客户端。
目前发现infuse并不能显示实际内容为ASS格式的SRT字幕，现在如果检测到infuse的UA会不转换SRT。
如果你在使用其他客户端并且也无法处理内容为ASS格式的SRT字幕，请告诉我。

**Comment by RiderLty** [comment]
docker-compose我没怎么用过哈，试试双引号行么？或者转义下。🤔
上面那个我也遇到了，初步猜测可能是处理时间较长导致,现在，现在加上了字体与字幕缓存，可以试试。

**Comment by entaroartanis114514** [comment]
那个变量也可能是我操作有问题,一直弄不上，改用env或者docker run就可以弄上去了。
佬，后面这个版本我现在看他一直在加载字体不处理字幕。
因为我下的那个50G字体包,字体有点多,感觉今天晚上看不出来效果了，明天我再看看效果。
佬，字体下次重开后还需要重新扫描吗？
![屏幕截图 2024-09-01 231310](https://github.com/user-attachments/assets/a4b1f43a-18ed-4d85-8c65-d553ae00b60a)

**Comment by entaroartanis114514** [comment]
佬，这个扫50G的字体用了差不多一个小时左右。
同一个视频PC客户端会弹出下面的错误并且出不来字幕。
2024/09/02 01:06:06 | stdout | INFO:     ip - "GET /emby/Videos/61101/ebf46282cae9ed895e65ba30d528433e/Subtitles/2/0/Stream.ssa?api_key=key HTTP/1.0" 200 OK
2024/09/02 01:06:06 | stdout | 出错了: 'default'  返回原始内容
2024/09/02 01:06:06 | stdout | 原始大小: 37938
WEB会出现下面的错误然后无兼容的流，手机也会弹出上面PC客户端的错误但又正常播放带有字幕
stdout | 出错了: not enough values to unpack (expected 2, got 1)  返回原始内容
2024/09/02 01:37:34 | stdout | 原始大小: 0
SRT字幕内网手机和TV会命中缓存两次，然后出不来字幕但可以播放。如果通过域名反代fontinass的端口访问SRT字幕视频日志只命中缓存一次但跟之前一样没字幕卡住。而PC和WEB内外网只会命中一次然后可以显示SRT字幕

佬，我看不太懂这些怎么回事了。
上一版除了双端同时播放一个srt影片这个小BUG其它没碰到什么，这版虽然快了但是BUG看不懂

**Comment by RiderLty** [comment]
字幕出错只会不显示字幕，无兼容的流应该是别的什么地方出问题了。

现在这个版本的逻辑是，nginx将客户端请求/videos/(.*)/Subtitles反向代理到字体处理程序。

字体处理程序去请求原始字幕，然后将处理后的字幕返回给nginx。

即使出错了，也应该是返回原始字幕的。

如果你在使用nginx，推荐直接单独添加一条配置，容器只要暴露一个8011，或者直接运行```main.py```都可以。

```
location ~* /videos/(.*)/Subtitles {
    #这里填字体处理程序的地址
    proxy_pass http://192.168.3.3:8011;
}
```
扫字体太慢，可以把```/localFontMap.json```映射到容器外，避免重复扫描。下面是我的完整命令，你可以参考下。
```
docker run
  -d
  --name='fontinass'
  -e 'DEV'='true'
  -e 'EMBY_SERVER_URL'='http://192.168.3.3:7096'
  -e 'SRT_2_ASS_FORMAT'='Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding'
  -e 'SRT_2_ASS_STYLE'='Style: Default,楷体,20,&H03FFFFFF,&H00FFFFFF,&H00000000,&H02000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1'
  -e 'CACHE_SIZE'='1024'
  -p '8011:8011/tcp'
  -p '8097:8012/tcp'
  -v '/mnt/user/storage/Fonts/':'/fonts':'rw'
  -v '/mnt/user/storage/assinfontsDEV':'/DEV':'rw'
  -v '/mnt/user/appdata/fontinass/localFontMap.json':'/localFontMap.json':'rw' 'riderlty/fontinass'
```

**Comment by RiderLty** [comment]
发下SRT文件和SRT_2_ASS_STYLE，SRT_2_ASS_FORMAT看看？这个错误看起来是SRT转ASS出错了 。
刚才添加了DEBUG功能，设置环境变量DEV=true，会显示处理前后的字幕，可以看下。

**Comment by entaroartanis114514** [comment]
佬这两个就是我一直在用的SRT字幕。DEBUG我等下看看什么情况
[两个字幕.zip](https://github.com/user-attachments/files/16838013/default.zip)
```这两个就是佬你发的默认格式
SRT_2_ASS_FORMAT='Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding'
SRT_2_ASS_STYLE='Style: Default,楷体,20,&H03FFFFFF,&H00FFFFFF,&H00000000,&H02000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1'
```
![image](https://github.com/user-attachments/assets/9a41843a-4b2e-422f-aca6-0d7570471306)

**Comment by entaroartanis114514** [comment]
佬，这四个有点乱，我是用html直接变后缀成log了。佬你换成html就比较清晰一些
四个客户端都是播放了两个影片，手机确实是中了两次缓存，
[PC客户端.log](https://github.com/user-attachments/files/16838639/PC.log)
[TV.log](https://github.com/user-attachments/files/16838640/TV.log)
[手机.log](https://github.com/user-attachments/files/16838641/default.log)
[网页.log](https://github.com/user-attachments/files/16838642/default.log)

**Comment by RiderLty** [comment]
```银魂完结篇：直到永远的万事屋 (2013) - 1080p.zh-CN.srt```  这个里面，格式是错误的，导致解析Event的时候，无法获取到文本，于是在子集化的时候，就没有把对应的字放进去。

[SRT字幕的颜色以及一些特效的设置](https://blog.csdn.net/lishirong/article/details/41674123)

比如
```
1
00:00:02,440 --> 00:00:10,820
{\fs30\fad(500500)\an8}本字幕由「白月字幕组」制作 仅限内部学习交流 请于24小时内删除 若您喜欢请支持购买正版
```

正确的写法应该是

```
1
00:00:02,440 --> 00:00:10,820
{\fs30\fad(500,500)\an8}本字幕由「白月字幕组」制作 仅限内部学习交流 请于24小时内删除 若您喜欢请支持购买正版
```
原本的即使是SRT，也是不能实现淡入淡出的。
修改之后就正确显示了。

建议还SRT还是尽量收纯文本的吧。

**Comment by entaroartanis114514** [comment]
啊...佬主要的不是特效和排版问题，但还是谢谢佬解决这个问题了。
是0,0,Default那串字符的问题，之前版本字幕是没有这东西的，还有手机端需要从头开始播放才有字幕，如果挪动进度条就会没字幕，以及TV的SRT字幕出不来。
那个魔女的字幕我根据佬发的文章看了下文本是没有任何特效的，但同样是拖动进度条后出不来字幕以及出现0,0,Default那串。
这些在之前刚刚更新SRT那个版本是没有的，所以想问下佬怎么回事

**Comment by entaroartanis114514** [comment]
佬，还是不行...  Defaul前面的数字就是第几个字幕文本，Defaul后是字体格式？
第一张图是银魂的那个字幕日志输出
![image](https://github.com/user-attachments/assets/53195a66-044c-4d04-bedd-c5e5db842b1b)
第二张图是银魂在手机端转为ASS字幕后
![Screenshot_20240903_204347](https://github.com/user-attachments/assets/e7b0c941-0e82-44e5-9a5f-ba1d8d2b2112)
第三张图是魔女那个纯文本SRT转ASS字幕后
![Screenshot_20240903_204440](https://github.com/user-attachments/assets/bb8d3c54-3ee5-46f0-9baa-c6d83cc56a71)

**Comment by RiderLty** [comment]
![6fafa70145c17b25a53715a1421e07ce](https://github.com/user-attachments/assets/98dcf02a-591c-4069-b7ba-c06452889d44)
![e78bdce284366a0a05789907cfa024f4](https://github.com/user-attachments/assets/6413cd3b-1bfc-474c-b19a-b678d72a8718)
![905b63c710f21d6c85e4b5417949aed2](https://github.com/user-attachments/assets/b5454a5a-ee72-4f27-8b96-adb4e4f6a0df)
🤔，应该是客户端的问题了。
[test.zip](https://github.com/user-attachments/files/16849257/test.zip)

**Comment by entaroartanis114514** [comment]
佬，我这里服务端是4.8.0.66测试版
TV客户端是小秘的TV 2.0.95g常规版
手机是官方最新版的3.4.21和小秘的3.2.32-17.41都不行...
PC客户端是3.0.20-3.0的小秘版本可以正常显示。
佬，能问下你用的版本吗？
以及佬如果能否留个之前版本的镜像？

**Comment by RiderLty** [comment]
这个[emby.apk](https://fonts.storage.rd5isto.org/emby.apk)，有一说TV版已经没啥必要了吧，手机版设置下显示为TV就可以了。

**Comment by entaroartanis114514** [comment]
[佬，是exo播放器的问题，对ASS字幕支持有问题。](https://emby.media/community/index.php?/topic/125510-emby-android%E4%BD%BF%E7%94%A8%E7%AC%AC%E4%B8%89%E6%96%B9%E6%92%AD%E6%94%BE%E5%99%A8%E6%97%A0%E6%B3%95%E5%8A%A0%E8%BD%BD%E5%A4%96%E6%8C%82%E7%9A%84%E5%AD%97%E5%B9%95)
手机端之前因为mpv播放有时候黑屏所以关了...手机端用mx播放器和PC端potplayer都是正常的。
电视端我估计也是exo播放器...
电脑端因为开着mpv播放器所以没事。
绷不住了,弄了这么长时间是因为播放器的问题，答辩exo，气死了
TV版是因为我家电视安装不了emby安卓版，估计跟安卓版本又有关系...今天开始打算换苹果盒子用infuse了

**Comment by entaroartanis114514** [comment]
之前版本转的字幕应该格式简单一些，exo可以显示出来。
后面更改格式复杂一些，exo就出不来了。
佬，问题解决了。
这个问题是播放器对字幕支持有问题。
解决办法是要不然换ASS格式转换的时候简单一些，要不然就用外部播放器。

**Comment by RiderLty** [comment]
build了一个旧版本的 [riderlty/fontinass:njsmode](https://hub.docker.com/layers/riderlty/fontinass/njsmode/images/sha256-2222cdecf477fcef5ddce421ae25c6799ef597a521b7909ce46da221595ba69c?context=explore)

之前是用njs请求，python只负责bytes => ASS => 处理后的ASS => bytes，njs只替换内容。

后面要加点功能，就改成nginx只负责反向代理字幕请求到python，没用njs了。

希望这个你能用吧🥰

**Comment by entaroartanis114514** [comment]
谢谢佬，但还是不行。
应该是处理字幕Dialogue语句的那段问题，字幕显示时间和使用字幕特效那段复杂了一些？
EXO识别不了所以会出现0,0，Default,,0,0,0,,    然后挪动进度条后不知道时间轴也就不会再显示字幕。
佬，这个方法是对的。其它播放器都可以，就这个exo不可以，
