### ISSUE TITLE
字幕字体格式缺失，unicodes缺失？还是uuencode编码问题。

### ISSUE THREAD

**Issue by mcratt** [RiderLty/fontInAss#15]
换了个播放软件，字体有缺失很明显显示出来。
这是uharfbuzz子集化后的效果：
![uharfbuzz1](https://github.com/user-attachments/assets/f59eb4a6-e63d-4fe2-99a2-4f6d0074a636)
![uharfbuzz2](https://github.com/user-attachments/assets/c4937eab-ae35-4547-a87b-12d481c536be)

这是fontTools的Subsetter子集化后效果，使用footTools时候已经卸载uharfbuzz，应该不存在fontTools自动调用uharfbuzz问题。
![Subsetter1](https://github.com/user-attachments/assets/c90317ac-21e9-4eb5-9c35-6d1f3aa83590)
![Subsetter2](https://github.com/user-attachments/assets/9920a12c-2f52-41f4-ace4-4bdabb97d6a8)

可以看出2个子集化都出现同样的问题？所以猜测是unicodes或者编码问题。

```python
def makeOneEmbedFontsText(args):
    # 在每个子进程中设置日志
    logging.basicConfig(level=logging.ERROR, format="%(asctime)s - %(levelname)s - %(message)s")
    fontBytes, fontName, unicodeSet, = args
    bio = BytesIO()
    bio.write(fontBytes[0])
    bio.seek(0)
    font = TTFont(bio)
    if fontBytes is None:
        return f"缺少字体 {fontName}", None
    else:
        try:
            originNames = font["name"].names

            subsetter = Subsetter()
            subsetter.populate(unicodes=unicodeSet)
            subsetter.subset(font)

            font["name"].names = originNames
            fontOutIO = BytesIO()
            font.save(fontOutIO)
            enc = uuencode(fontOutIO.getvalue())
            return None, f"fontname:{fontName}_0.ttf\n{enc}\n"
        except Exception as e:
            logger.error(f"子集化{fontName}出错 : \n{traceback.format_exc()}")
            return f" {fontName} : {str(e)}", None
```

这是fontTools的，uharfbuzz用最新代码的

**Comment by RiderLty** [comment]
ass能否发一下？🤔 如果都出现了问题，大概率是解析出问题了。

**Comment by mcratt** [comment]
> ass能否发一下？🤔 如果都出现了问题，大概率是解析出问题了。

吃完饭发你，这集只要是这几个字都是没字体格式

**Comment by mcratt** [comment]
> ass能否发一下？🤔 如果都出现了问题，大概率是解析出问题了。

[香格里拉边境 - S01E21 - 跑腿、养成、攻略.zho.forced.zip](https://github.com/user-attachments/files/17656127/-.S01E21.-.zho.forced.zip)

**Comment by RiderLty** [comment]
多线程读取字体的问题😰，已修复。
