### ISSUE TITLE
大佬求教unraid安装的方法

### ISSUE THREAD

**Issue by lingqi606** [RiderLty/fontInAss#2]
“如果你有本地字体，将字体目录映射到/fonts下即可被自动识别
  -v /path/to/your/fonts3:/fonts/dir3 \”
这个是把下载的字体放到系统fonts文件夹，然后/fonts么。
“ -v /etc/localFontMap.json:/localFontMap.json \”
localFontMap.json这个是啥，我没找到。如果能在b站详细说一下就好了，小白不会弄，谢谢大佬。

**Comment by RiderLty** [comment]
如果没有本地字体，用到字体的时候，程序会即时从CDN上下载字体，见[fontMap.json](https://github.com/RiderLty/fontInAss/blob/main/fontMap.json)

这样虽然速度比较慢但是CDN里有VCB的50多G的字体包，而且有缓存在，也还行其实。

但是如果你有本地字体包，或者发现缺少了某个字体，则可以添加自己的本地字体。

程序监控/fonts文件夹，只要扔在/fonts目录下即可自动识别，所以本地字体包映射到/fonts下任意路径即可。

localFontMap.json 是本地字体的数据库，本地字体太多更新docker重建本地数据库读取会特别慢。

把这个持久化就不用每次重新构建本地字体数据库了。

**Comment by RiderLty** [comment]
[Unraid部署](https://github.com/RiderLty/fontInAss?tab=readme-ov-file#unraidb%E9%83%A8%E7%BD%B2)
添加了Unraid的模板，记得移除不需要的功能

**Comment by lingqi606** [comment]
感谢大佬，大佬费心了。
