### ISSUE TITLE
关于字体匹配的问题

### ISSUE THREAD

**Issue by Mister-album** [RiderLty/fontInAss#22]
部分ass字幕在被引用的时候名字中会带字形大小，比如我手头有个字幕引用了‘xxx 常规’，这个xxx字体确实是存在的，但ass文件引用的时候不规范，名字后面带了个‘常规’的字形
这种是否能做个判断，如果找不到字体就尝试对字体文件名通过空格进行分隔，把最后一个空格的内容剔除掉再匹配一次字体，这样的话一些不规范的字体名称引用也能匹配到相应的字体，提高匹配率

**Comment by RiderLty** [comment]
用potplayer试了下，```xxx 常规```与```xxx``` 在播放器里是两个字体，即使存在```xxx``` ，```xxx 常规```也不会用```xxx```来渲染。

**Comment by Mister-album** [comment]
> 用potplayer试了下，`xxx 常规`与`xxx` 在播放器里是两个字体，即使存在`xxx` ，`xxx 常规`也不会用`xxx`来渲染。

只是部分特殊字体会这样而已，比如我手头的这个‘何尼玛-细体’，查看字体的详细信息时会发现他的字体家族是‘何尼玛-细体’，子字体家族为‘常规‘，这种情况播放器是能匹配到的，但程序就不认了。。。。。。
![QQ20241125-212825](https://github.com/user-attachments/assets/5d66f9b7-4914-47f1-8f88-677418daadd5)
另附上原版的字体跟我提取出来的单个ttf字体
https://wwmf.lanzout.com/isymx2g999sj密码:c5cg

**Comment by Mister-album** [comment]
另附上我查看字体信息的网站：[FontEditor](https://font.qqe2.com/)，不过应该是有现成的工具识别字体信息的

**Comment by Mister-album** [comment]
> ![image](https://private-user-images.githubusercontent.com/135112135/389559116-873ccc4a-46b0-43da-a678-dae2919cc548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDQyMzMsIm5iZiI6MTczMjU0MzkzMywicGF0aCI6Ii8xMzUxMTIxMzUvMzg5NTU5MTE2LTg3M2NjYzRhLTQ2YjAtNDNkYS1hNjc4LWRhZTI5MTljYzU0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxNDEyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjU5N2M2YWVlYzE1MWJjNmNjOWQ0OTIzYWNlNmRkNWQ4OWE2OWQxYWQ3ODgyNDFhYTg4ZDMxOWM5ZjJlMDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DSNlsSi-CClhwAZhOlHvZopBLVI4epIStpcnrKlSEn8)
> 
> 你是说 字体命名成这样的，在播放机里会被渲染成`何尼玛-细体` ？
> 
> 播放器能发下吗？

是的，播放器我用PotPlayer、MPV都可以正常加载出这个字体，不过我这个字幕好像是带点特效的，我一并传上来吧
[带着智能手机闯荡异世界 - S01E05 - 第 5 集.default.zh-Hans.txt](https://github.com/user-attachments/files/17904190/-.S01E05.-.5.default.zh-Hans.txt)
手动改名成ass就行

**Comment by mcratt** [comment]
建议在FontDetail表在加一列记录sub_family，然后查询时候先完全匹配再模糊查询

![1](https://github.com/user-attachments/assets/a6c540d9-3e26-449f-8de8-b64b8cd41483)

**Comment by RiderLty** [comment]
https://bbs.acgrip.com/thread-3848-9-1.html 
此问题在FontLoaderSub里亦有记载

[NotoSansCJKtc-Bold 1.004.otf](https://fonts.storage.rd5isto.org/NotoSansCJKtc-Bold%201.004.otf) ：
![image](https://github.com/user-attachments/assets/6fabefe2-9636-4ce0-851c-f9f7c765cb8d)

[NotoSansCJKtc-Bold 2.001.otf](https://fonts.storage.rd5isto.org/NotoSansCJKtc-Bold%202.001.otf) ：
![image](https://github.com/user-attachments/assets/899e344f-fb37-4f46-8189-5cfe37b8d1ad)




| | 1.004	| 2.001 | 
| -------- | -------- | -------- |
| Family	| Noto Sans CJK TC Bold	| Noto Sans CJK TC |
| Sub family	| Regular | 	Bold |
| Full font name	| Noto Sans CJK TC Bold	| Noto Sans CJK TC Bold |

只安装了[NotoSansCJKtc-Bold 2.001.otf](https://fonts.storage.rd5isto.org/NotoSansCJKtc-Bold%202.001.otf)的情况下，使用Full font name ```Noto Sans CJK TC Bold``` 下面的ass也是无法匹配对应字体的，但是```何尼玛-细体```用Family和Full font name都可以。

```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Noto Sans CJK TC Bold,120,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,3,2,15,15,15,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 3,0:00:00.00,0:59:00.00,Default,,0,0,0,fx,字体 ABC 测试
```
推测```何尼玛-细体```这个字体里面是有什么flag标注了🤔

如果是的话，[NotoSansCJKtc-Bold 2.001.otf](https://fonts.storage.rd5isto.org/NotoSansCJKtc-Bold%202.001.otf)这个字体经过修改，也可以通过Full font name ```Noto Sans CJK TC Bold``` 来匹配到。

正确理方式应该是建立数据库的时候找到这个标记，再将Full font name也作为可以匹配的fontName加到数据库里。

有待研究。

**Comment by mcratt** [comment]
那存多个FULL_NAME，还是存SUBFAMILY，存FULL_NAME就好办得多，多几行而已，存SUBFAMILY的话多一列但是需要对应关系，查询也变得复杂。

![123123](https://github.com/user-attachments/assets/b3527695-7782-43bf-8b32-73baedf6b36b)

**Comment by mcratt** [comment]
单存full_name似乎也不妥，有的full_name不带属性，有的full_name并不全属性

![123](https://github.com/user-attachments/assets/4b2bac1f-7040-40f4-88a7-4dc10c1eab53)
![456](https://github.com/user-attachments/assets/75a258f7-2270-453e-89f6-4db77f799797)

**Comment by RiderLty** [comment]
根据libass的[find_font](https://github.com/libass/libass/blob/159cefc9074a9b816d62c6b4251521ab515ecaca/libass/ass_fontselect.c#L709) 的逻辑，字体匹配是先匹配family_name，如果找到了则根据粗体，斜体信息打一个分并记录。
如果family_name没有匹配，则尝试匹配full_name 或者 postscript_name，且一旦匹配成功则记录score为0并立即终止匹配。
最后取score最小的字体。
这么来看的话，应该记录family_name，full_name，postscript_name 然后按照优先级分别查找并返回。
但是实际测试中，部分可以用postscript_name或者full_name匹配成功，部分则不行。

**Comment by mcratt** [comment]
> 根据libass的[find_font](https://github.com/libass/libass/blob/159cefc9074a9b816d62c6b4251521ab515ecaca/libass/ass_fontselect.c#L709) 的逻辑，字体匹配是先匹配family_name，如果找到了则根据粗体，斜体信息打一个分并记录。 如果family_name没有匹配，则尝试匹配full_name 或者 postscript_name，且一旦匹配成功则记录score为0并立即终止匹配。 最后取score最小的字体。 这么来看的话，应该记录family_name，full_name，postscript_name 然后按照优先级分别查找并返回。 但是实际测试中，部分可以用postscript_name或者full_name匹配成功，部分则不行。


看看这样有没有问题
![12312312](https://github.com/user-attachments/assets/8757ee61-431c-44ce-b0be-91cfeeb155e0)

```python
    def get_fontinfo_by_familyname(self, family_name: str):
        try:
            print(f"输入为：{family_name}")
            start = time.perf_counter_ns()

            # 合并精确匹配和模糊匹配的查询语句
            stmt = (
                select(FontDetail.file_path, FontDetail.family_name, FontDetail.family_index, FontDetail.sub_family_list, FontInfo.file_size)
                .select_from(FontDetail)
                .join(FontInfo, FontDetail.file_path == FontInfo.file_path)
                .where(
                    or_(
                        FontDetail.family_name == family_name,  # 精确匹配
                        func.instr(family_name, FontDetail.family_name) > 0  # 模糊匹配
                    )
                )
                .order_by(FontInfo.file_size)
            )
            # 执行查询
            result = self.db_session.execute(stmt).first()
            if result:
                db_file_path, db_family_name, db_family_index, db_sub_family_list, db_file_size = result
                if family_name != db_family_name:
                    # 如果是模糊匹配且匹配到了子家族名
                    sub_family = family_name.replace(db_family_name, "").strip()
                    if sub_family in db_sub_family_list:
                        res = db_file_path, db_family_index
                        logger.debug(f"{family_name} 查询耗时{(time.perf_counter_ns() - start) / 1000000:.2f}ms")
                        return res
                else:
                    # 精确匹配的结果
                    res = db_file_path, db_family_index
                    logger.debug(f"{family_name} 查询耗时{(time.perf_counter_ns() - start) / 1000000:.2f}ms")
                    return res
            else:
                return None
        except SQLAlchemyError as e:
            logger.error(f"查询字体信息时出错: {e}")
            return None
```

**Comment by RiderLty** [comment]
这个逻辑对```何尼玛-细体```确实可以，但是对 Noto Sans CJK TC 与 Noto Sans CJK TC Bold 不行。

如字幕里用到了Noto Sans CJK TC Bold ，但是实际只存在 Noto Sans CJK TC 。

这个虽然可以给他匹配到，但是却不能被播放器渲染。不如直接报错。

**Comment by mcratt** [comment]
> 这个逻辑对`何尼玛-细体`确实可以，但是对 Noto Sans CJK TC 与 Noto Sans CJK TC Bold 不行。
> 
> 如字幕里用到了Noto Sans CJK TC Bold ，但是实际只存在 Noto Sans CJK TC 。
> 
> 这个虽然可以给他匹配到，但是却不能被播放器渲染。不如直接报错。

那这个问题算是解决了吧，你提到这个问题总感觉有点复杂，既然只存在 Noto Sans CJK TC，如果他需要用Bold，但是Noto Sans CJK TC不存在Bold 还是记录了Bold属性，感觉是字体问题。

**Comment by RiderLty** [comment]
对的，这个就是最操蛋的地方了，这个2.001的Noto Sans CJK TC是有Bold属性的，但是实际上并不会用这个来渲染 Noto Sans CJK TC Bold。
| |1.004 | 2.001|
| -- |-- | --|
|Family | Noto Sans CJK TC Bold | Noto Sans CJK TC|
|Sub family | Regular | Bold|
|Full font name | Noto Sans CJK TC Bold | Noto Sans CJK TC Bold|


```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Noto Sans CJK TC,120,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,3,2,15,15,15,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 3,0:00:00.00,0:59:00.00,Default,,0,0,0,fx,我能吞下玻璃而不伤身体 
```

这里把2.001的Noto Sans CJK TC子集化，且他是有Bold属性的。

![image](https://github.com/user-attachments/assets/94be5abd-4bf7-4637-a352-e5fe8b3018ea)

给子集化后的ass文件里修改下字体名称
```
Style: Default,Noto Sans CJK TC Bold,120,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,3,2,15,15,15,1
```

居然就不能正常渲染了 🤨

**Comment by mcratt** [comment]
> 对的，这个就是最操蛋的地方了，这个2.001的Noto Sans CJK TC是有Bold属性的，但是实际上并不会用这个来渲染 Noto Sans CJK TC Bold。
> 
> 1.004	2.001
> Family	Noto Sans CJK TC Bold	Noto Sans CJK TC
> Sub family	Regular	Bold
> Full font name	Noto Sans CJK TC Bold	Noto Sans CJK TC Bold
> ```
> [V4+ Styles]
> Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
> Style: Default,Noto Sans CJK TC,120,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,3,2,15,15,15,1
> 
> [Events]
> Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
> Dialogue: 3,0:00:00.00,0:59:00.00,Default,,0,0,0,fx,我能吞下玻璃而不伤身体 
> ```
> 
> 这里把2.001的Noto Sans CJK TC子集化，且他是有Bold属性的。
> 
> ![image](https://private-user-images.githubusercontent.com/135112135/390035678-94be5abd-4bf7-4637-a352-e5fe8b3018ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzEzMTIsIm5iZiI6MTczMjY3MTAxMiwicGF0aCI6Ii8xMzUxMTIxMzUvMzkwMDM1Njc4LTk0YmU1YWJkLTRiZjctNDYzNy1hMzUyLWU1ZmU4YjMwMThlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMTMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODIwZTNlNzI0YzFmODhiMGFiMjYwODRhZWZiMzI3MmQzMDJjZmJhZjA4YTU0NzAzNGZlODg0YjMxY2JjMDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tF2KDTFCJXZDM1KnOwitMyc2m-TMsuIWeqJ2IYYEDqs)
> 
> 给子集化后的ass文件里修改下字体名称
> 
> ```
> Style: Default,Noto Sans CJK TC Bold,120,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,3,2,15,15,15,1
> ```
> 
> 居然就不能正常渲染了 🤨

猜测是不能直接这样改名字的，就像之前提到的table中的name，字体不像图像可以用数组去存储，里面可能还有字形，方向等等

**Comment by RiderLty** [comment]
完美解决方案可能只有按照libass解析字幕读取字体的方式重写遍python的。😥 头大

**Comment by mcratt** [comment]
> 完美解决方案可能只有按照libass解析字幕读取字体的方式重写遍python的。😥 头大

重写哪个方法，解析ASS那个吗，要是有点实例去验证下就好了。

**Comment by RiderLty** [comment]
> > 完美解决方案可能只有按照libass解析字幕读取字体的方式重写遍python的。😥 头大
> 
> 重写哪个方法，解析ASS那个吗，要是有点实例去验证下就好了。

正在看libass的源码。准备给他匹配字体的逻辑搞清楚复刻下。

验证可以用ffmpeg指定字体文件夹尝试渲染字幕看是否有字体未找到的报错。
```
ffmpeg -f lavfi -i color=#000000@0:s=1920x1080 -vf "subtitles=input.ass:fontsdir=/mnt/storage/Projects/fontInAss/fonts" -ss 3 -vframes 1 -vsync 0 -f image2pipe -vframes 1 -  > /dev/null 
```

**Comment by RiderLty** [comment]
已解决，更新下docker
