### ISSUE TITLE
关于family_name是否准确

### ISSUE THREAD

**Issue by mcratt** [RiderLty/fontInAss#23]
之前以为这个family_name是某些日文导致乱码，然后今天用新代码提取信息时候发现family_name与旧代码的数量不一样，因此想看看哪个正确。旧代码用的gen_font_info()里面的

![123](https://github.com/user-attachments/assets/0e95b080-1450-462f-be7d-63f8a86c4d3b)

```python
print("\n旧代码fontTool:")
for file_path in fontdir_files:
    with open(file_path, "rb") as f:
        data = f.read()
    sfntVersion = data[:4]
    fonts = TTCollection(BytesIO(data)).fonts if sfntVersion == b"ttcf" else [TTFont(BytesIO(data))]
    print(f"\n字体名：{file_path}")
    for index, font in enumerate(fonts):
        family = set()
        print(f"下标：{index}")
        for record in font["name"].names:
            # print(f"{record.nameID} - 字符：{record}")
            if record.nameID == 1:
                fontName = str(record).strip()
                print(fontName)
```

**Comment by RiderLty** [comment]
字体能发下吗？

我用```/超级字体整合包 XZ/精简包/日文/DynaFont（华康）/DFSoGei-W7 & DFPSoGei-W7 & DFGSoGei-W7.ttc```这个试了下：

![image](https://github.com/user-attachments/assets/85e49f32-cbc6-4b01-9b49-10847f5a4903)
```python
from io import BytesIO
import os
from fontTools.ttLib import TTCollection, TTFont

def gen_font_info( file_path):
        with open(file_path, "rb") as f:
            data = f.read()
        sfntVersion = data[:4]
        print('sfntVersion == b"ttcf" ? ', sfntVersion == b"ttcf")
        fonts = TTCollection(BytesIO(data)).fonts if sfntVersion == b"ttcf" else [TTFont(BytesIO(data))]
        file_size = os.path.getsize(file_path)
        file_mtime = int(os.path.getmtime(file_path))
        font_count = len(fonts)
        # 直接构造 font_info_list 和 font_detail_list
        font_info_list = [{
            "file_path": file_path,
            "file_size": file_size,
            "file_mtime": file_mtime,
            "font_count": font_count
        }]
        font_detail_list = []
        for index, font in enumerate(fonts):
            print("\nfontIndex = ",index)
            family = []
            for record in font["name"].names:
                if record.nameID == 1:
                    fontName = str(record).strip()
                    print("RECID = ",record.nameID , ":" ,fontName)
        return font_info_list, font_detail_list

# gen_font_info(r"fonts/何尼玛-细体 常规.ttf")
gen_font_info(r"fonts/DFSoGei-W7 & DFPSoGei-W7 & DFGSoGei-W7.ttc")
```

**Comment by mcratt** [comment]
> 字体能发下吗？
> 
> 我用`/超级字体整合包 XZ/精简包/日文/DynaFont（华康）/DFSoGei-W7 & DFPSoGei-W7 & DFGSoGei-W7.ttc`这个试了下：
> 
> ![image](https://private-user-images.githubusercontent.com/135112135/389792899-85e49f32-cbc6-4b01-9b49-10847f5a4903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTYzMDEsIm5iZiI6MTczMjU5NjAwMSwicGF0aCI6Ii8xMzUxMTIxMzUvMzg5NzkyODk5LTg1ZTQ5ZjMyLWNiYzYtNGIwMS05YjQ5LTEwODQ3ZjVhNDkwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzg0MTc1YWMzZjQ4ZDZhYjc4NDczOTFlMWVjYmJjMDgzZjRiZWIxYjE4MWQ3NWUwMTM5OTc0ZDZmOThlZjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z04Bn8xLEs7TYMHlVQsergrZYDXNsx1jepyFMPx3Fw4)
> 
> ```python
> from io import BytesIO
> import os
> from fontTools.ttLib import TTCollection, TTFont
> 
> def gen_font_info( file_path):
>         with open(file_path, "rb") as f:
>             data = f.read()
>         sfntVersion = data[:4]
>         print('sfntVersion == b"ttcf" ? ', sfntVersion == b"ttcf")
>         fonts = TTCollection(BytesIO(data)).fonts if sfntVersion == b"ttcf" else [TTFont(BytesIO(data))]
>         file_size = os.path.getsize(file_path)
>         file_mtime = int(os.path.getmtime(file_path))
>         font_count = len(fonts)
>         # 直接构造 font_info_list 和 font_detail_list
>         font_info_list = [{
>             "file_path": file_path,
>             "file_size": file_size,
>             "file_mtime": file_mtime,
>             "font_count": font_count
>         }]
>         font_detail_list = []
>         for index, font in enumerate(fonts):
>             print("\nfontIndex = ",index)
>             family = []
>             for record in font["name"].names:
>                 if record.nameID == 1:
>                     fontName = str(record).strip()
>                     print("RECID = ",record.nameID , ":" ,fontName)
>         return font_info_list, font_detail_list
> 
> # gen_font_info(r"fonts/何尼玛-细体 常规.ttf")
> gen_font_info(r"fonts/DFSoGei-W7 & DFPSoGei-W7 & DFGSoGei-W7.ttc")
> ```

[font.zip](https://github.com/user-attachments/files/17912714/font.zip)

**Comment by RiderLty** [comment]
用```jpname = str(record.toBytes().decode('shift_jis', errors='ignore'))```可以正常解码，不过咋判断这个编码呢🥲

**Comment by mcratt** [comment]
> 用`jpname = str(record.toBytes().decode('shift_jis', errors='ignore'))`可以正常解码，不过咋判断这个编码呢🥲

https://github.com/fonttools/fonttools/blob/21d22ae30f88b76fab5575f5f2e882b142ee1c08/Lib/fontTools/misc/encodingTools.py#L51-L60            这个可以解决，不过需要多获取几个参数，不过我看解码出来也是跟前面的一样，那是不是我那个新代码解码就是正确的。

**Comment by RiderLty** [comment]
测试下如果结果一样的，直接用hb给替换掉得了。

**Comment by RiderLty** [comment]
测试下要是没问题，给替换成HB的吧

**Comment by mcratt** [comment]
OK，不过要等uharfbuzz那里更新0.44，他刚合并发布新版本可能还要一段时间。需要新版本一个函数。
