### ISSUE TITLE
Unraid下Error

### ISSUE THREAD

**Issue by Sandings** [RiderLty/fontInAss#26]
🤖 22:31:11.710 .INFO    本地字体文件夹:/fonts
🤖 22:31:12.734 .INFO    开始检查数据库与目录的一致性...
🤖 22:31:12.754 .INFO    监控中:/fonts
🌏 22:31:12.807 .INFO    Started server process [11]
🌏 22:31:12.807 .INFO    Waiting for application startup.
🌏 22:31:12.808 .INFO    Application startup complete.
🌏 22:31:12.808 .INFO    Uvicorn running on http://0.0.0.0:8011 (Press CTRL+C to quit)
🤖 22:51:46.792 .INFO    本地字体文件夹:/fonts
🤖 22:51:47.422 .INFO    开始检查数据库与目录的一致性...
🤖 22:51:47.442 .INFO    监控中:/fonts
🌏 22:51:47.501 .INFO    Started server process [9]
🌏 22:51:47.501 .INFO    Waiting for application startup.
🌏 22:51:47.502 .INFO    Application startup complete.
🌏 22:51:47.502 .INFO    Uvicorn running on http://0.0.0.0:8011 (Press CTRL+C to quit)
🤖 22:51:52.981 .INFO    字幕URL: http://192.168.50.186:8096/
🤖 22:51:53.131 .INFO    判断编码:{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}
🤖 22:51:53.133 .INFO    子集化嵌入 0.16ms
🤖 22:51:53.140 .ERROR   处理出错，返回原始内容 : 
Traceback (most recent call last):
  File "//src/main.py", line 157, in proxy_pass
    srt, bytes = await process(subtitleBytes, userHDR)
  File "/src/assSubsetter.py", line 116, in process
    head, tai = assText.split("[Events]")
ValueError: not enough values to unpack (expected 2, got 1)

🌏 22:51:53.140 .INFO    192.168.50.161:4423 - "GET / HTTP/1.1" 200

**Comment by RiderLty** [comment]
```🤖 22:51:52.981 .INFO 字幕URL: http://192.168.50.186:8096/```
这里没有获取到字幕的URL，正确的应该是类似这样的：
```🤖 15:02:18.572 .INFO 字幕URL: http://192.168.3.3:7096/emby/Videos/25477/mediasource_25477/Subtitles/2/Stream.ass?SetFilename=true```

**Comment by RiderLty** [comment]
可以设置下LOG_LEVEL为DEBUG，发完整的log看下。

**Comment by mcratt** [comment]
字幕URL都空了，就是第一步的request已经是空了，大概率是客户端问题了，不是所有客户端都支持的，PC有tsukimi，安卓有emby小秘版，这2个测试下来使用MPV播放器的基本是完美支持。

**Comment by akane145** [comment]
我用的unraid也是这样，我切换了个docker版本就好了，换到latest可以正常使用

**Comment by RiderLty** [comment]
知道了，unraid模板是无nginx版本的。回头换成默认的去。

**Comment by Sandings** [comment]
> 知道了，unraid模板是无nginx版本的。回头换成默认的去。

谢谢
