### ISSUE TITLE
求教一下群晖上怎么安装

### ISSUE THREAD

**Issue by moonking2020** [RiderLty/fontInAss#3]

**Comment by moonking2020** [comment]
我在win下面装完，就一直重启
![image](https://github.com/user-attachments/assets/0d9e07bc-d216-4273-9738-15842d2f2c62)

**Comment by RiderLty** [comment]
没有群辉，不知道啥样的，直接输docker命令也不行吗？这个图片里报错好像是把本地字体数据库映射成文件夹了。
